name: Verwonderaar
favicon: null
layout_spectrum: 0.9849831832107157
typography_spectrum: 0.024993836181238294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#05060a'
    - '#3b3738'
    - '#a28b32'
    - '#ccb772'
  brandStrength: 0.6358243022114038
  lightness: 0.8140886870678514
  saturation: 0.16198506532236934
  rhythmicContrast: 0.5799641546327621
purpose: []
